// generated by "sampctl package init"
#include <a_samp>
#include "rdialogs-pages.inc"

main() {}

public OnPlayerText(playerid, text[])
{
	AddPlayerDialogPages(playerid, "Nama\tLevel\tSkor");
	for (new i = 0; i < 35; i++)
	{
		new row[128];
		format(row, sizeof(row), "Player_%d\t%d\t%d", i + 1, random(100), random(9999));
		AddPlayerDialogPages(playerid, row);
	}

	ShowPlayerDialogPages(
		playerid,
		"TestDialog",
		DIALOG_STYLE_TABLIST_HEADERS,
		"Daftar Pemain",
		"Pilih",
		"Tutup",
		20,
		"{FFFF00}Halaman Berikutnya >>>",
		"{FFFF00}<<< Halaman Sebelumnya"
	);
	return 1;
}

DialogPages:TestDialog(playerid, response, listitem, inputtext[])
{
    if (!response) return 1;
    new itemStr[256];
    format(itemStr, sizeof(itemStr), "Kamu memilih item: %s", rdialogpages_ListitemString[playerid][listitem]);
    SendClientMessage(playerid, 0x00FF00FF, itemStr);
    return 1;
}